import numpy as np
import pandas as pd
import argparse, os, glob, warnings, sys
warnings.filterwarnings('ignore')
sys.path.append(os.path.dirname(__file__))
from data_utils import *
from epi_utils import *

parser = argparse.ArgumentParser()

parser.add_argument("-o", dest='output_dir', type=str, required=True, help='Directory to save files to')

cmd_line_args = parser.parse_args()

output_dir = cmd_line_args.output_dir


# ordinal encoding: bl_afbprog --> smear
smear_encoding_dict = {6: np.nan, # I think this was already done in their data cleaning
                       5: np.nan, # I think this was already done in their data cleaning
                       0: 0, # no AFB
                       4: 1, # scanty
                       1: 2, # +
                       2: 3, # ++
                       3: 4, # +++
                      }
                                 

def get_time_to_culture_conversion(single_sample_combined_sputum_results):
    '''
    This function computes the TCC for a single sample in the sputum results dataframe. A TTP is only valid if the culture result is tb_positive.
    '''

    # keep only samples up to 12 (in case the month 5 samples are still in the table)
    single_sample_combined_sputum_results = single_sample_combined_sputum_results.query("sample_num <= 12")

    # replacement that the BMC group did. This is only for the TCC calculation. Keep the original samples unchanged
    single_sample_combined_sputum_results['result'] = single_sample_combined_sputum_results['result'].replace('tb_positive_contaminated', 'tb_positive')
    
    start_positive = single_sample_combined_sputum_results.query("result=='tb_positive'").sample_num.min()

    if start_positive is None:
        raise ValueError(f"There is no start culture positivity time for {pid}")
        
    # the TCC will be the first of two negative result that are not followed by a positive result
    # don't consider positive smear because smear test can detect dead bacteria, which won't grow in the culture.
    end_positive = single_sample_combined_sputum_results.query("result=='tb_positive'").sample_num.max()

    # exclude the month 5 culture (sample_num = 20) from the TCC computation
    post_last_positive_results = single_sample_combined_sputum_results.query("sample_num > @end_positive").reset_index(drop=True)

    # initialize as None variable
    start_negative = None

    # check that there are at least 2 negative results, otherwise don't do the search below
    if len(post_last_positive_results.query("result=='tb_negative'")) >= 2:

        # check that they are consecutive results
        for i, row in post_last_positive_results.iterrows():

            # check that it's not the last culture, in which case there won't be a second negative afterwards
            if row['result'] == 'tb_negative' and i != len(post_last_positive_results) - 1:
                
                if post_last_positive_results.result.values[i+1] == 'tb_negative':
                    
                    # get the sample number of the first negative sample
                    start_negative = row['sample_num']

                    # can break because we already checked above that there are no positive cultures or smear grades afterwards
                    break

    # if no culture conversion (no event), then the patient did not culture convert, so take the maximum number of weeks
    if start_negative is None:
        # start_negative = 12 # the last culture sample in the treatment window. Don't consider 
        #start_negative = single_sample_combined_sputum_results.sample_num.max()

        # take the time of the last known positive culture. They will be censored at this time. If there are contaminated or single negative cultures after this time,
        # we can't interpret them because they are inconclusive. 
        # Exclude the values above 12 because those aren't weeks

        # if you take the last negative sample, sometimes you take a negative sample that occurs before a positive sample. The time of the last positive sample is probably the most informative time
        # take the last known time when the patient was smear positive or culture positive
        start_negative = end_positive
        
        culture_convert = 0
    else:
        culture_convert = 1

    # keep track of patients who culture converted
    # all patients in this study have TB (microbiologically confirmed), so take week 1 as the starting time
    return culture_convert, start_negative



# this is a table of the original cultures, TTP, and smear graade values in long format
df_combined_cultures = pd.read_csv(f"{output_dir}/combined_culture_results.csv")

# read in the imputed cultures generated by imputation_culture.Rmd
df_imputed_cultures = pd.read_csv(f"{output_dir}/imputed_cultures.csv")

df_TCC_imputed = pd.DataFrame(columns = ['pid', 'culture_convert', 'TCC', 'imp_num'])
i = 0

for imp in df_imputed_cultures['.imp'].unique():
    
    # get all the imputed cultures from df_imputed_cultures. They have column names culture_N
    df_single_imp_cultures = df_imputed_cultures.loc[(df_imputed_cultures['.imp']==imp)][['pid'] + list(df_imputed_cultures.columns[df_imputed_cultures.columns.str.contains('culture_')])]
    
    df_single_imp_cultures = df_single_imp_cultures.melt(value_name='result', id_vars='pid')
    
    df_single_imp_cultures['sample_num'] = df_single_imp_cultures['variable'].str.split('_').str[-1].astype(int)
    
    # keep only cultures within the first 12 weeks.
    df_single_imp_cultures = df_single_imp_cultures.query("sample_num <= 12")
    
    # merge with smear. Smear grade is used to compute TCC
    df_single_imp_cultures = df_combined_cultures[['pid', 'sample_num', 'smear_grade']].merge(df_single_imp_cultures, on=['pid', 'sample_num'])
    
    for pid in df_single_imp_cultures.pid.unique():
        culture_convert, TCC = get_time_to_culture_conversion(df_single_imp_cultures.query("pid==@pid"))
        df_TCC_imputed.loc[i, :] = [pid, culture_convert, TCC, imp]
        i += 1
        
        
# the first "imputation" (imp_num = 0) is the original data
df_TCC_imputed.to_csv(f"{output_dir}/TCC_{df_TCC_imputed.imp_num.nunique()-1}_imputations.csv", index=False)