import numpy as np
import pandas as pd
import glob, os, vcf, warnings, shutil, subprocess, re
import scipy.stats as st
from Bio import Seq, SeqIO
from Bio.Data import CodonTable
from collections import Counter

h37Rv_path = "~/MtbLongitudinalDiversity/H37Rv"
h37Rv_seq = SeqIO.read(os.path.join(h37Rv_path, "GCF_000195955.2_ASM19595v2_genomic.gbff"), "genbank")
h37Rv_genes = pd.read_csv(os.path.join(h37Rv_path, "mycobrowser_h37rv_genes_v4.csv"))
h37Rv_coords = pd.read_csv(os.path.join(h37Rv_path, "h37Rv_coords_to_gene.csv.gz"), compression='gzip')


def estimate_mutation_rates(variants_df, h37Rv_seq):
    
    # Count substitutions
    sub_counts = Counter(zip(variants_df["REF"], variants_df["ALT"]))

    # Count genome-wide base composition
    genome_base_counts = Counter(h37Rv_seq.seq)

    # Compute per-base mutation rates
    mu = {}
    for ref in "ACGT":
        ref_total = genome_base_counts.get(ref, 0)
        for alt in "ACGT":
            if ref != alt:
                mu[(ref, alt)] = sub_counts.get((ref, alt), 0) / ref_total

    return mu



def expected_mutations_per_gene(regions_lst, h37Rv_seq, mu):
    
    expected = {}
    gene_lengths = {}

    for region in regions_lst:
        
        if region in h37Rv_genes.Symbol.values:
            start = h37Rv_genes.query("Symbol==@region").Start.values[0]
            end = h37Rv_genes.query("Symbol==@region").End.values[0]
            
        elif 'NC' in region:
            start = h37Rv_coords.query("region==@region").pos.min()
            end = h37Rv_coords.query("region==@region").pos.max()
            
        else:
            raise ValueError(f"{region} not found!")
            
        seq = str(h37Rv_seq.seq[start-1:end]).upper()

        counts = Counter(seq)

        E = 0.0
        for ref in "ACGT":
            for alt in "ACGT":
                if ref != alt:
                    E += counts.get(ref, 0) * mu[(ref, alt)]

        expected[region] = E
        gene_lengths[region] = [start, end, len(seq)]

    return pd.Series(expected, name="Expected"), pd.DataFrame(gene_lengths, index=['Start', 'End', 'Length']).T


# codon-aware helper functions
standard_table = CodonTable.unambiguous_dna_by_name["Standard"]
stop_codons = set(standard_table.stop_codons)

def mutate_codon(codon, pos, alt):
    codon_list = list(codon)
    codon_list[pos] = alt
    return "".join(codon_list)

def classify_mutation(codon, new_codon):
    
    # pass in a codon and return the amino acid. If the codon is not found, return * because stop codons are not in the dictionary generated by the standard table
    aa1 = standard_table.forward_table.get(codon, "*")
    aa2 = standard_table.forward_table.get(new_codon, "*")
    
    # track mutations to nonsyn (aa2) separately because they are strongly selected against in the MTBC
    if aa1 == aa2:
        return "synonymous"
    else:
        if aa2 != '*':
            return "nonsynonymous"
        else:
            return "nonsense"


def expected_mutations_per_region(regions_lst, h37Rv_seq, mu, h37Rv_genes):
    
    expected = {}
    gene_lengths = {}

    for region in regions_lst:
        
        if region in h37Rv_genes.Symbol.values:
            row = h37Rv_genes.query("Symbol==@region").iloc[0]
            start, end, sense = row.Start, row.End, row.Strand
            is_coding = True
            
        elif 'NC_' in region:
            start = h37Rv_coords.query("region==@region").pos.min()
            end = h37Rv_coords.query("region==@region").pos.max()
            is_coding = False
            sense = '+' # default to positive sense for intergenic regions, tho it doesn't matter
            
        else:
            raise ValueError(f"{region} not found!")
            
        seq = str(h37Rv_seq.seq[start-1:end]).upper()
        
        if sense != '+':
            seq = str(Seq.Seq(seq).reverse_complement())
        
        # E_syn, E_nonsyn, E_nonsense, E_total = 0.0, 0.0, 0.0, 0.0
        E_syn, E_nonsyn, E_total = 0.0, 0.0, 0.0

        # Only apply codon model to coding regions
        if is_coding:

            for i in range(0, len(seq), 3):
                codon = seq[i:i+3]
                                
                # skip ambiguous codons
                if any(b not in "ACGT" for b in codon):
                    continue

                for pos in range(3):
                    ref = codon[pos]

                    for alt in "ACGT":
                        if alt == ref:
                            continue

                        new_codon = mutate_codon(codon, pos, alt)
                        mut_type = classify_mutation(codon, new_codon)
                        
                        if mut_type == "synonymous":
                            E_syn += mu[(ref, alt)]
                        else:
                            E_nonsyn += mu[(ref, alt)]
                        # elif mut_type == "nonsynonymous":
                        #     E_nonsyn += mu[(ref, alt)]
                        # else:
                        #     E_nonsense += mu[(ref, alt)]
                        
                        E_total += mu[(ref, alt)]

        else:
            # use the original nucleotide model for intergenic regions because there are no syn or nonsyn mutations
            counts = Counter(seq)
            for ref in "ACGT":
                for alt in "ACGT":
                    if ref != alt:
                        E_total += counts.get(ref, 0) * mu[(ref, alt)]

        expected[region] = {
            "E_syn": E_syn,
            "E_nonsyn": E_nonsyn,
            # "E_nonsense": E_nonsense,
            "E_total": E_total
        }
        
        gene_lengths[region] = [start, end, len(seq)]

    return pd.DataFrame(expected).T, pd.DataFrame(gene_lengths, index=['Start','End','Length']).T


def count_observed_mutations(variants_df, h37Rv_seq, h37Rv_genes):
    
    observed = {}
    
    regions_lst = np.concatenate([
        variants_df.query("~Region.str.contains('NC')").GENE.unique(),
        variants_df.query("Region.str.contains('NC')").Region.unique()
    ])
    
    for region in regions_lst:
        region_df = variants_df[(variants_df.GENE==region) | (variants_df.Region==region)]
        row = h37Rv_genes.query("Symbol==@region") if region in h37Rv_genes.Symbol.values else None

        if row is not None and len(row) > 0:
            # coding
            row = h37Rv_genes.query("Symbol==@region").iloc[0]
            start, end, sense = row.Start, row.End, row.Strand
            
            seq = str(h37Rv_seq.seq[start-1:end]).upper()

            # O_syn, O_nonsyn, O_nonsense = 0, 0, 0
            O_syn, O_nonsyn = 0, 0
            L = len(seq) - (len(seq)%3)
            seq = seq[:L]

            for idx, row_var in region_df.iterrows():

                if sense == '+':
                    pos = row_var.POS - start  # 0-based in gene
                    codon_start = (pos // 3) * 3
                    codon_pos = pos % 3
                    codon = seq[codon_start:codon_start+3]
                else:
                    pos = end - row_var.POS  # 0-based in gene
                    codon_start = (pos // 3) * 3
                    codon_pos = pos % 3
                    codon = Seq.Seq(seq).reverse_complement()[codon_start:codon_start+3]

                if len(codon) != 3 or any(b not in "ACGT" for b in codon):
                    raise ValueError(f"Incorrect codon at {pos} in {region}")

                ref = row_var.REF
                alt = row_var.ALT

                # in the variant table, REF and ALT are always in positive sense
                # so if the gene is negative sense, then alt needs to be reverse complemented. 
                # codon is already reverse complemented if needed, and codon_pos is the index within the codon
                if sense == '+':
                    new_codon = codon[:codon_pos] + alt + codon[codon_pos+1:]
                else:
                    new_codon = codon[:codon_pos] + str(Seq.Seq(alt).reverse_complement()) + codon[codon_pos+1:]

                mut_type = classify_mutation(codon, new_codon)
                
                if mut_type == "synonymous":
                    O_syn += 1
                else:
                    O_nonsyn += 1
                # elif mut_type == "nonsynonymous":
                #     O_nonsyn += 1
                # else:
                #     O_nonsense += 1
            
            observed[region] = {
                "O_syn": O_syn,
                "O_nonsyn": O_nonsyn,
                # "O_nonsense": O_nonsense,
                "O_total": len(region_df)
            }
        else:
            # intergenic
            observed[region] = {"O_total": len(region_df)}
    
    return pd.DataFrame(observed).T.fillna(0)


def poisson_enrichment_test(observed, expected):
    
    df = pd.concat([observed, expected], axis=1).fillna(0)

    df["Fold_Enrichment"] = df["Observed"] / df["Expected"].replace(0, np.nan)

    # One-sided test: enrichment
    df["Enrich_pval"] = st.poisson.sf(df["Observed"] - 1, df["Expected"])

    return df.sort_values("Twosided_pval")


# def permutation_test(variants_df, observed, genes_lst, genome_seq, n_perm=1000, seed=1):
    
#     rng = np.random.default_rng(seed)

#     # Genome positions by base
#     base_positions = {
#         b: np.where(np.array(list(genome_seq)) == b)[0]
#         for b in "ACGT"
#     }
    
#     gene_lengths = {}
    
#     for gene in genes_lst:
#         if gene not in h37Rv_genes.Symbol.values:
#             print(f"{gene} is not a gene")
#         else:
#             start = h37Rv_genes.query("Symbol==@gene").Start.values[0]
#             end = h37Rv_genes.query("Symbol==@gene").End.values[0]
#             gene_lengths[gene] = end - start + 1

#     gene_offsets = np.cumsum([0] + list(gene_lengths.values()))
#     gene_names = list(gene_lengths.keys())

#     def position_to_gene(pos):
#         idx = np.searchsorted(gene_offsets, pos, side="right") - 1
#         return gene_names[idx] if 0 <= idx < len(gene_names) else None

#     perm_counts = {g: [] for g in genes_lst}

#     ref_alt = list(zip(variants_df["REF"], variants_df["ALT"]))

#     for _ in range(n_perm):
#         counts = Counter()

#         for ref, alt in ref_alt:
#             pos = rng.choice(base_positions[ref])
#             gene = position_to_gene(pos)
#             if gene is not None:
#                 counts[gene] += 1

#         for g in genes_lst:
#             perm_counts[g].append(counts.get(g, 0))

#     # Compute empirical p-values
#     results = []
#     for i, g in enumerate(genes_lst):
#         obs = observed.get(g, 0)
#         perm = np.array(perm_counts[g])
#         p = (np.sum(perm >= obs) + 1) / (n_perm + 1)
#         results.append((g, p))

#     return pd.DataFrame(results, columns=["GENE", "Permutation_pval"]).set_index("GENE")


# def perform_poisson_enrichment_test_codon_aware(variants_df, keep_lineages=None):
            
#     if keep_lineages is not None:
#         variants_df = variants_df.query("Lineage in @keep_lineages")
#         assert len(variants_df) > 0
        
#     # genes_lst = variants_df.query("Variant_Type != 'Intergenic'").GENE.unique()
    
#     # include intergenic regions too. Need to get names from different columns though
      # regions_lst = np.concatenate([
      #     variants_df.query("~Region.str.contains('NC')").GENE.unique(),
      #     variants_df.query("Region.str.contains('NC')").Region.unique()
      # ])
#     # do full dataset, then separate by lineage as well. KEEP intergenic variants for estimating genome-wide mutation rate
#     mu = estimate_mutation_rates(variants_df.drop_duplicates(subset=['SampleID', 'POS', 'REF', 'ALT']), h37Rv_seq)
#     print(f"Genome-wide mutation rate: {mu}\n")

#     expected, df_gene_lengths = expected_mutations_per_gene_codon(
#                                                                 regions_lst, 
#                                                                 h37Rv_seq, 
#                                                                 mu,
#                                                             )
        
#     # Names come from different columns for coding and non-coding variants
#     observed = pd.concat([variants_df.query("Variant_Type != 'Intergenic'").groupby("GENE").size().rename("Observed"),
#                           variants_df.query("Variant_Type == 'Intergenic'").groupby("Region").size().rename("Observed")
#                          ])

#     poisson_results = poisson_enrichment_test(observed, expected)
    
#     return poisson_results.merge(df_gene_lengths, left_index=True, right_index=True), mu



def poisson_enrichment_test(observed_df, expected_df):
    """
    Poisson-based enrichment test for coding and intergenic regions.
    Returns a consistent DataFrame with columns:
    syn_pval, syn_fold, nonsyn_pval, nonsyn_fold, nonsense_pval, nonsense_fold,
    total_pval, total_fold
    """
    results = {}

    for region in observed_df.index:
        obs = observed_df.loc[region]
        exp = expected_df.loc[region]

        region_results = {}

        # intergenic region prefix
        if region[:3] == 'NC_':
            
            O_total = obs["O_total"]
            E_total = exp["E_total"]

            # coding columns set to NaN
            region_results["syn_pval"] = np.nan
            region_results["syn_fold"] = np.nan
            region_results["nonsyn_pval"] = np.nan
            region_results["nonsyn_fold"] = np.nan
            # region_results["nonsense_pval"] = np.nan
            # region_results["nonsense_fold"] = np.nan

            # intergenic enrichment
            region_results["total_pval"] = st.poisson.sf(O_total - 1, E_total)
            region_results["total_fold"] = O_total / (E_total + 1e-8)

        else:
            total_O, total_E = 0, 0
            
            for mut_type in ["syn", "nonsyn"]:#, "nonsense"]:
                O = obs[f"O_{mut_type}"]
                E = exp[f"E_{mut_type}"]

                if E == 0:
                    p_val = np.nan
                    fold = np.nan
                else:
                    p_val = st.poisson.sf(O - 1, E)
                    fold = O / E

                region_results[f"{mut_type}_pval"] = p_val
                region_results[f"{mut_type}_fold"] = fold

                total_O += O
                total_E += E

            # total enrichment across all coding mutations
            region_results["total_pval"] = st.poisson.sf(total_O - 1, total_E)
            region_results["total_fold"] = total_O / (total_E + 1e-8)

        results[region] = region_results

    combined_results = pd.DataFrame(results).T.merge(observed_df, left_index=True, right_index=True).merge(expected_df, left_index=True, right_index=True)

    for col in combined_results.columns[combined_results.columns.str.endswith('_pval')]:
        
        # exclude the intergenic regions when correcting syn/nonsyn/nonsense p-values because they don't have them
        combined_results[f'{col}_Bonferroni'] = combined_results[col] * len(combined_results.dropna(subset=col))
        combined_results.loc[combined_results[f'{col}_Bonferroni'] > 1, f'{col}_Bonferroni'] = 1
        
    return combined_results



def perform_codon_aware_enrichment_test(variants_df, h37Rv_seq=h37Rv_seq, h37Rv_genes=h37Rv_genes, h37Rv_coords=h37Rv_coords, keep_lineages=None, neutral_bg_only=False):
    
    if keep_lineages is not None:
        variants_df = variants_df.query("Lineage in @keep_lineages")
    
    regions_lst = np.concatenate([
        variants_df.query("~Region.str.contains('NC')").GENE.unique(),
        variants_df.query("Region.str.contains('NC')").Region.unique()
    ])
    
    # because of variants occurring in overlapping genes, there are duplicate positions. This is needed for accurately counting mutations, 
    # but it will inflate mu because of double counting, so drop duplicates before estimating mu
    # if use only silent and intergenic variants to estimate mu
    if neutral_bg_only:
        mu = estimate_mutation_rates(
            variants_df.query("Variant_Type in ['Silent', 'Intergenic']").drop_duplicates(subset=['SampleID','POS','REF','ALT']),
            h37Rv_seq
        )
    else:
        mu = estimate_mutation_rates(
            variants_df.drop_duplicates(subset=['SampleID','POS','REF','ALT']),
            h37Rv_seq
        )
    
    expected_df, gene_lengths_df = expected_mutations_per_region(
        regions_lst, h37Rv_seq, mu, h37Rv_genes
    )
    
    # deduplicate variants on the same haplotype and codon. If they occur on the same codon, they are a single instance of a mutation
    variants_df_for_counting_obs = pd.concat([variants_df.query("Variant_Type != 'Intergenic'").drop_duplicates(['SampleID', 'GENE', 'HGVS_C']),
                                              variants_df.query("Variant_Type == 'Intergenic'")
                                             ]).sort_values(['pid', 'SampleID', 'POS']).reset_index(drop=True)

    observed_df = count_observed_mutations(variants_df_for_counting_obs, h37Rv_seq, h37Rv_genes)
    
    results_df = poisson_enrichment_test(observed_df, expected_df)
    
    return results_df.merge(gene_lengths_df, left_index=True, right_index=True), mu