import numpy as np
import pandas as pd
import glob, os, argparse, time, vcf
import warnings
warnings.filterwarnings('ignore')
from utils import *

parser = argparse.ArgumentParser()

parser.add_argument("-d", "--depth", dest='depth_file', type=str, required=True, help='Depth file to use to filter out low quality low frequency variants.')
parser.add_argument("-i", "--input", dest='input_file', type=str, required=True, help='TSV file to further filter')
parser.add_argument("-o", "--output", dest='output_file', type=str, required=True, help='BED file of coordinates to transform to another coordinate system')
parser.add_argument("-g", "--genome", dest='genome', type=str, help='Full path to genome assembly')
parser.add_argument("--AF_min", dest='AF_min', type=float, default=0.05, help='AF threshold for an unfixed variant')
parser.add_argument("--AF_max", dest='AF_max', type=float, default=0.95, help='AF threshold for a fixed variant')

cmd_line_args = parser.parse_args()
depth_file = cmd_line_args.depth_file
input_file = cmd_line_args.input_file
output_file = cmd_line_args.output_file
genome = cmd_line_args.genome
AF_min = cmd_line_args.AF_min
AF_max = cmd_line_args.AF_max

dir_name = os.path.dirname(os.path.dirname(input_file))


def filter_high_quality_lowAF_variants(input_file, depth_file, lowAF_variants_bed_file, AF_min=0.05, AF_max=0.95):

    # CSV file generated by SnpSift
    df_variants = pd.read_csv(input_file, sep='\t')    
    
    df_variants['SampleID'] = os.path.basename(input_file).split('.')[0]
    
    # apply QC filters
    df_lowAF_variants = apply_freebayes_lowAF_QCfilters(df_variants, AF_min=AF_min, AF_max=AF_max)
        
    # require that all low-AF variants occur in areas where the depth is at least half the median depth
    df_depth = pd.read_csv(depth_file, compression='gzip', header=None, sep='\t', names=['CHROM','POS', 'DEPTH'], nrows=1)

    depth_min = df_depth['DEPTH'].median() / 2
    # depth_max = df_depth['DEPTH'].median() * 2

    df_lowAF_variants = df_lowAF_variants.query("DP >= @depth_min")
        
    # split SNVs into MNVs
    df_lowAF_variants_split_MNVs = split_MNPs_into_SNPs(df_lowAF_variants)
    
    # recombine. df_lowAF_variants_split_MNVs will contain all SNVs and MNVs after splitting, so just combine with the indels
    df_lowAF_variants = pd.concat([df_lowAF_variants.query("REF.str.len() != ALT.str.len()"), 
                                   df_lowAF_variants_split_MNVs]).reset_index(drop=True)

    # write a BED-formatted file. Keep all the other fields in the CSV to easily get variant information
    # first get the chromosome name, which is the name of the contig from the hybrid assembly
    # chrom = df_lowAF_variants.CHROM.unique()[0]
    chrom = df_depth.CHROM.values[0]

    # add chromosome name to the dataframe
    df_lowAF_variants['CHROM'] = chrom

    # 0-based half-open intervals
    df_lowAF_variants['BEG'] = df_lowAF_variants['POS'] - 1

    # interval should cover the full variant, so take the length difference between REF and ALT, absolute value, then add 1 so that it includes the full region
    # this works because all variants have been left-aligned
    df_lowAF_variants['END'] = df_lowAF_variants['BEG'] + (np.abs(df_lowAF_variants['ALT'].str.len() - df_lowAF_variants['REF'].str.len()) + 1)

    # save BED file
    save_cols = ['DP', 'RO', 'AO', 'AF', 'MQM', 'MQMR', 'SRF', 'SRR', 'SAF', 'SAR', 'SRP', 'SAP', 'RPP', 'RPPR', 'RPL', 'RPR']
        
    df_lowAF_variants[['CHROM', 'BEG', 'END', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER'] + save_cols].to_csv(lowAF_variants_bed_file, sep='\t', index=False)
    
    
if not os.path.isfile(genome):
    raise ValueError(f"{genome} does not exist")
    

filter_high_quality_lowAF_variants(input_file,
                                   depth_file,
                                   output_file,
                                   AF_min=AF_min,
                                   AF_max=AF_max
                                  )