import numpy as np
import pandas as pd
import glob, os, argparse, time, vcf
import warnings
warnings.filterwarnings('ignore')
from utils import *

parser = argparse.ArgumentParser()

parser.add_argument("-d", "--depth", dest='depth_file', type=str, required=True, help='Depth file to use to filter out low quality low frequency variants.')
parser.add_argument("-i", "--input", dest='input_file', type=str, required=True, help='TSV file to further filter')
parser.add_argument("-o", "--output", dest='output_file', type=str, required=True, help='BED file of coordinates to transform to another coordinate system')
parser.add_argument("-g", "--genome", dest='genome', type=str, help='Full path to genome assembly')
parser.add_argument("--pilon", dest='use_pilon', action="store_true", help="Use pilon output, instead of freebayes (default)")

cmd_line_args = parser.parse_args()
depth_file = cmd_line_args.depth_file
input_file = cmd_line_args.input_file
output_file = cmd_line_args.output_file
genome = cmd_line_args.genome
use_pilon = cmd_line_args.use_pilon

dir_name = os.path.dirname(os.path.dirname(input_file))


def filter_high_quality_lowAF_variants(input_file, depth_file, lowAF_variants_bed_file, use_pilon=False):

    # CSV file generated by SnpSift
    df_variants = pd.read_csv(input_file, sep='\t')    
    
    # apply QC filters
    if use_pilon:
        df_lowAF_variants = apply_pilon_lowAF_QCfilters(df_variants)
    else:
        df_lowAF_variants = apply_freebayes_lowAF_QCfilters(df_variants)
        
    # require that all low-AF variants occur in areas where the depth is at least half the median depth
    df_depth = pd.read_csv(depth_file, compression='gzip', header=None, sep='\t', names=['CHROM','POS', 'DEPTH'])

    depth_min = df_depth['DEPTH'].median() / 2
    # depth_max = df_depth['DEPTH'].median() * 2

    # need to use total depth (TD), not DP, for pilon which is the depth of valid reads (concordantly paired and not soft-clipped)
    if use_pilon:
        df_lowAF_variants = df_lowAF_variants.query("TD >= @depth_min")# & TD <= @depth_max")
    else:
        df_lowAF_variants = df_lowAF_variants.query("DP >= @depth_min")# & DP <= @depth_max")
    
    # use the total depth in df_depth, rather than the freebayes DP value? DP is the total depth, not filtered to be high quality reads only
    low_depth_sites = df_depth.query("DEPTH < @depth_min").POS.values
    # high_depth_sites = df_depth.query("DEPTH > @depth_max").POS.values
    
    df_lowAF_variants = df_lowAF_variants.query("POS not in @low_depth_sites")# & POS not in @high_depth_sites")

    # write a BED-formatted file. Keep all the other fields in the CSV to easily get variant information
    # first get the chromosome name, which is the name of the contig from the hybrid assembly
    chrom_name = df_depth['CHROM'].unique()[0]

    # add chromosome name to the dataframe
    df_lowAF_variants['CHROM'] = chrom_name

    # 0-based half-open intervals
    df_lowAF_variants['BEG'] = df_lowAF_variants['POS'] - 1

    # interval should cover the full variant, so take the length difference between REF and ALT, absolute value, then add 1 so that it includes the full region
    # this works because all variants have been left-aligned
    df_lowAF_variants['END'] = df_lowAF_variants['BEG'] + (np.abs(df_lowAF_variants['ALT'].str.len() - df_lowAF_variants['REF'].str.len()) + 1)

    # save BED file
    if use_pilon:
        save_cols = ['IMPRECISE', 'DP', 'TD', 'BQ', 'MQ', 'QD', 'BC', 'QP', 'PC', 'IC', 'DC', 'XC', 'AC', 'AF']
    else:
        save_cols = ['DP', 'RO', 'AO', 'AF', 'MQM', 'MQMR', 'SRF', 'SRR', 'SAF', 'SAR', 'SRP', 'SAP', 'RPP', 'RPPR', 'RPL', 'RPR']
        
    df_lowAF_variants[['CHROM', 'BEG', 'END', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER'] + save_cols].to_csv(lowAF_variants_bed_file, sep='\t', index=False)
    
    
if not os.path.isfile(genome):
    raise ValueError(f"{genome} does not exist")
    

filter_high_quality_lowAF_variants(input_file,
                                   depth_file,
                                   output_file,
                                   use_pilon=use_pilon
                                  )