---
title: "Linear Mixed Model Low AF Variants"
output: html_document
date: "2025-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages('caret')

library("lme4")
library('caret')
library('pROC')
library(ggplot2)
library(broom)
library(broom.mixed)
```

```{r}
fit_model <- TRUE
model_dir <- "unmixed_only_v2"

model_dir = paste("/home/sak0914/MtbLongitudinalDiversity/lowAF_variant_calling/variantDetector/", model_dir, sep="")

# this is fixed variants (AF > 0.95) for all isolates, both train and validation
# df_fixed <- read.csv(paste(model_dir, "/fixed_variants.csv.gz", sep=""))
df_train <- read.csv(paste(model_dir, "/training_data.csv", sep=""))

predictors <- c("COV_RATIO", "CLIPPED_BASES_RATIO", "DISCORDANT_READS_RATIO", "Mean_BQ_ALT_allele", "SAF_prop_deviation_from_half")

# just get X for df_fixed
# X_fixed <- df_fixed[, predictors]
# fixed_samples <- df_fixed[['SampleID']]

# Extract X and y
X_train <- df_train[, predictors]
y_train <- df_train[['Real']]
train_samples <- df_train[['SampleID']]

df_val <- read.csv(paste(model_dir, "/validation_data.csv", sep=""))

# Extract X and y
X_val <- df_val[, predictors]
val_samples <- df_val[['SampleID']]

dim(X_train)
dim(X_val)
table(df_train$Real)
```

```{r}
# --- Standardize predictors ---
X_train_mean <- sapply(X_train, mean, na.rm = TRUE)
X_train_sd <- sapply(X_train, sd, na.rm = TRUE)

save(X_train_mean, file = paste(model_dir, "/X_train_mean.RData", sep=""))
save(X_train_sd, file = paste(model_dir, "/X_train_sd.RData", sep=""))

# Scale training predictors
X_train_scaled <- as.data.frame(scale(X_train, center = X_train_mean, scale = X_train_sd))
X_val_scaled <- as.data.frame(scale(X_val, center = X_train_mean, scale = X_train_sd))
# X_fixed_scaled <- as.data.frame(scale(X_fixed, center = X_train_mean, scale = X_train_sd))

# combine into dataframes
df_train_scaled = cbind(X_train_scaled, Real = y_train, SampleID = train_samples)
df_val_scaled = cbind(X_val_scaled, SampleID = val_samples)
# df_fixed_scaled = cbind(X_fixed_scaled, SampleID = fixed_samples)

# then cbind the original df_val with identifier columns
# df_val_scaled = cbind(df_val_scaled, df_val[, c("POS", "REF", "ALT", "AF")])
# df_fixed_scaled = cbind(df_fixed_scaled, df_fixed[, c("POS", "REF", "ALT", "AF")])
```
    
    
```{r}
compute_metrics <- function(df, pred_col = "predicted", true_col = "Real", threshold = 0.5) {
  # Binarize predictions based on threshold
  df$pred_class <- ifelse(df[pred_col] >= threshold, 1, 0)
  
  # True positives, false positives, true negatives, false negatives
  TP <- sum(df$pred_class == 1 & df[true_col] == 1)
  FP <- sum(df$pred_class == 1 & df[true_col] == 0)
  TN <- sum(df$pred_class == 0 & df[true_col] == 0)
  FN <- sum(df$pred_class == 0 & df[true_col] == 1)
  
  # Metrics
  precision <- if ((TP + FP) == 0) NA else TP / (TP + FP)
  recall <- if ((TP + FN) == 0) NA else TP / (TP + FN)  # Sensitivity
  specificity <- if ((TN + FP) == 0) NA else TN / (TN + FP)
  
  # Return as a list
  return(list(
    precision = precision,
    recall = recall,
    specificity = specificity,
    sum_sens_spec = recall + specificity,
    sum_sens_prec = recall + precision,
    F1 = 2 * recall * precision / (recall + precision)
  ))
}
# Function to find best threshold
compute_best_binarization_threshold <- function(df, pred_col = "predicted", true_col = "Real", thresholds = seq(0, 1, 0.01)) {
  metrics <- sapply(thresholds, function(t) compute_metrics(df, pred_col, true_col, t))
  metrics_df <- as.data.frame(t(metrics))
  metrics_df$threshold <- thresholds
  
  best_row <- metrics_df[which.max(metrics_df$F1), ]
  best_thresh <- best_row$threshold
  
  return(best_thresh)
  # return(list(best_threshold = best_thresh, metrics = metrics_df))
}
```

```{r}
# Fit a mixed-effects logistic regression model
# Build the fixed-effects part of the formula
fixed_effects <- paste(predictors, collapse = " + ")

# Combine into full model formula
formula_str <- paste0("Real ~ ", fixed_effects, " + (1 | SampleID)")
model_formula <- as.formula(formula_str)

# glmer for random effects model. glm for fixed effects only
if (fit_model) {
  model <- glmer(
    model_formula,
    data = df_train_scaled,
    family = binomial(link = "logit")
  )
  
  # save the fitted model
  save(model, file = paste(model_dir, "/linear_mixed_model.RData", sep=""))

} else {
    load(paste(model_dir, "/linear_mixed_model.RData", sep=""))
}
 
# get predictions on the training set
df_train_scaled$predicted <- predict(model, type = "response")

# plot ROC AUC
train_roc_obj <- roc(df_train_scaled$Real, df_train_scaled$predicted)
plot(train_roc_obj)
auc(train_roc_obj)

# maximize the sum of sensitivity and precision
best_threshold <- compute_best_binarization_threshold(df_train_scaled)
print(paste("Best threshold", best_threshold))
```

```{r}
# get predictions on the training set. allow.new.levels = TRUE ignores random effects if there are new levels because they weren't seen during training. Needed if you have some samples in the validation data not in the training data
df_val$predicted <- predict(model, newdata = df_val_scaled, allow.new.levels = TRUE, type = "response")

# add the binary predictions, binarized at the best_threshold
df_val$pred_class <- ifelse(df_val$predicted >= best_threshold, 1, 0)

# get predictions on the training set. re.form = NA ignores random effects. Needed if you have some samples in the validation data not in the training data
df_train$predicted <- predict(model, newdata = df_train_scaled, type = "response")

# add the binary predictions, binarized at the best_threshold
df_train$pred_class <- ifelse(df_train$predicted >= best_threshold, 1, 0)

# get predictions for fixed variants, just to see
# df_fixed$predicted <- predict(model, newdata = df_fixed_scaled, re.form = NA, type = "response")
# df_fixed$pred_class <- ifelse(df_fixed$predicted >= best_threshold, 1, 0)

# save
write.csv(df_train, paste(model_dir, "/training_data_with_predictions.csv", sep=""), row.names = FALSE)
write.csv(df_val, paste(model_dir, "/validation_data_with_predictions.csv", sep=""), row.names = FALSE)
# write.csv(df_fixed, paste(model_dir, "/fixed_variants_with_predictions.csv", sep=""), row.names = FALSE)
```


```{r}
load(paste(model_dir, "/linear_mixed_model.RData", sep=""))
tidy_model <- tidy(model, effects = "fixed", conf.int = TRUE, conf.method = "Wald", exponentiate = TRUE)
# tidy_model <- tidy(model, effects = "fixed", conf.int = TRUE, conf.method = "boot", exponentiate = TRUE)

write.csv(tidy_model, paste(model_dir, "/linear_mixed_model_summary.csv", sep=""), row.names=FALSE)

term_labels <- c(
  "COV_RATIO" = "Coverage Ratio",
  "CLIPPED_BASES_RATIO" = "Clipped Bases Ratio",
  "DISCORDANT_READS_RATIO" = "Discordant Reads Ratio",
  "SAF_prop_deviation_from_half" = "Deviation from 50% Forward Reads",
  "Mean_BQ_ALT_Allele" = "Average Base Quality",
  "(Intercept)" = "Sample Random Effect"
)

plot = ggplot(tidy_model, aes(x = estimate, y = term)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey40") +
  scale_x_log10() +
  scale_y_discrete(labels = term_labels) +  # <--- change labels here
  theme_minimal() +
  labs(x = "Odds Ratio (95% CI)", y = NULL)

ggsave(paste(model_dir, "/forest_plot.svg", sep=""), plot = plot, width = 6, height = 4, dpi = 300)

View(tidy_model)
```