output_dir: "/n/data1/hms/dbmi/farhat/Sanjana/TRUST_lowAF"
fastq_dir: "/n/data1/hms/dbmi/farhat/fastq_db/TRUST_Illumina/TRUST.SRWGS.FQs.AllSets.RenamedAndLanesMerged"
isolates_to_run: "/home/sak0914/longitudinal_changes/lowAF_pipeline/TRUST_samples.tsv"
kraken_db: "/n/data1/hms/dbmi/farhat/mm774/References/Kraken2_DB_Dir/Kraken2_DB"
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.95
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"
taxid: 77643
bwa_mem_seed_length: 80
conda_dir: "/home/sak0914/Mtb_Megapipe"
exclude_regions_file: "BED_files/exclude_regions_50bp.bed"
phase_variation_ROI_file: "BED_files/phase_variation_ROI.bed"
WHO_catalog_regions_file: "BED_files/WHO_catalog_regions.bed"