---
title: "phybreak_analysis"
output: pdf_document
date: "2025-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages('coda')
install.packages('phytools')
install.packages("remotes")
remotes::install_github("donkeyshot/phybreak")

library(ape)
library(phybreak)
library(phytools)
```

```{r setup, include=FALSE}
# make phybreakdata object with function phybreak

# Read aligned FASTA file
seqs <- read.dna("~/MtbLongitudinalDiversity/transmission/L4_samples/SNP_concatenate_filtered.fasta", format = "fasta")

# Check sequence names
rownames(seqs)

df_sampling_dates <- read.csv("~/MtbLongitudinalDiversity/transmission/L4_samples/dates.csv")

# make sure the data column is a date object
df_sampling_dates$Sample_Date <- as.Date(df_sampling_dates$Sample_Date)

# Dates must be numeric, so make them relative to time 0, which is the reference date
t0 <- min(df_sampling_dates$Sample_Date)

# Sampling times in days since t0
df_sampling_dates$Sample_Date_numeric <- as.numeric(df_sampling_dates$Sample_Date - t0)

# Make a named vector for phybreak. setNames assigns names to an object. So you assign the sample IDs to each of the numeric dates
sampling_times <- setNames(df_sampling_dates$Sample_Date_numeric, df_sampling_dates$SampleID)

L4_dataset <- phybreakdata(sequences = seqs, sample.times = sampling_times)
```

```{r setup, include=FALSE}
# create phybreak object
# use 0.3 SNPs/genome/year. Transformed to days and the smaller SNP dataset, divide by 365 and number of sites in the MSA
mu <- 0.3 / ncol(as.matrix(seqs)) / 365

pb_results <- phybreak(L4_dataset, 
                       times = sampling_times, 
                       mu = mu,
                       gen.shape = 2, # shape param of gamma distribution of gen.mean
                       gen.mean = 365, # expected time between infection and infecting someone else (in days)
                       sample.shape = 2, # shape param of gamma distribution of sample.mean
                       sample.mean = 180, # expected time between infection and sampling (in days)
                       wh.model = 1, # effective size = 0, meaning that there is no within-host diversity 
                       wh.slope = 1,
                       est.gen.mean = TRUE, 
                       prior.mean.gen.mean = 1, 
                       prior.mean.gen.sd = Inf,
                       est.sample.mean = TRUE, 
                       prior.mean.sample.mean = 1,
                       prior.mean.sample.sd = Inf, 
                       est.wh.slope = TRUE, 
                       prior.wh.shape = 3,
                       prior.wh.mean = 1, 
                       use.tree = FALSE,
                       store.traces = TRUE,
                       )
```

```{r setup, include=FALSE}
plotTrans(pb_results)
plotPhylo(pb_results)
```

```{r setup, include=FALSE}
# exclude burn-in phase with burnin_phybreak
pb_results <- burnin_phybreak(pb_results, ncycles = 10000)
```

```{r setup, include=FALSE}
# post_results <- sample_phybreak(pb_results, nsample = 25000)

transmission_tree <- transtree(post_results, method="mtcc")

write.csv(transmission_tree, "~/MtbLongitudinalDiversity/transmission/L4_samples/inferred_tree.csv")
```

## Analyze the Results

```{r setup, include=FALSE}
plot(post_results, plot.which = "mpc")
```


```{r setup, include=FALSE}
mcmc_results <- get.mcmc(post_results)

# get the transmission tree
summary(mcmc_results[, c("mu", "mS", "mG")])
```

